import dns from 'dns';
import db, { initDatabase } from '../database';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.join(__dirname, '../../.env') });

// ép Node dùng DNS ngoài
dns.setServers(['8.8.8.8', '1.1.1.1']);

const ROLES = [
  { id: 1, key: 'admin', name: 'ADMIN (Đội trưởng)', description: 'Quyền tối cao', isActive: true },
  { id: 2, key: 'ns_leader', name: 'NS - Trưởng ban', description: 'Trưởng ban Nhân sự', isActive: true },
  { id: 3, key: 'ns_sub_leader', name: 'NS - Phó ban', description: 'Phó ban Nhân sự', isActive: true },
  { id: 4, key: 'ns_specialist', name: 'NS - Chuyên viên', description: 'Chuyên viên Nhân sự', isActive: true },
  { id: 10, key: 'tc_leader', name: 'TC - Trưởng ban', description: 'Trưởng ban Tài chính', isActive: true },
  { id: 11, key: 'tc_sub_leader', name: 'TC - Phó ban', description: 'Phó ban Tài chính', isActive: true },
  { id: 12, key: 'tt_leader', name: 'TT - Trưởng ban', description: 'Trưởng ban Truyền thông', isActive: true },
  { id: 13, key: 'tt_sub_leader', name: 'TT - Phó ban', description: 'Phó ban Truyền thông', isActive: true },
  {
    id: 5,
    key: 'other_leader',
    name: 'Ban khác - Trưởng ban',
    description: 'Trưởng ban các ban chuyên môn khác',
    isActive: true,
  },
  {
    id: 6,
    key: 'other_sub_leader',
    name: 'Ban khác - Phó ban',
    description: 'Phó ban các ban chuyên môn khác',
    isActive: true,
  },
  { id: 7, key: 'member', name: 'Thành viên', description: 'Thành viên chính thức', isActive: true },
  { id: 8, key: 'ctv', name: 'CTV', description: 'Cộng tác viên', isActive: true },
  { id: 9, key: 'other_role', name: 'Vai trò khác', description: 'Vai trò tùy chỉnh', isActive: true },
];

const PERMISSIONS = [
  // Thành viên
  { key: 'users:list:all', name: 'Xem danh sách toàn bộ thành viên', module: 'users' },
  { key: 'users:list:dept', name: 'Xem danh sách thành viên trong Ban', module: 'users' },
  { key: 'users:view_stats', name: 'Xem thống kê nhân sự', module: 'users' },
  { key: 'users:read:all', name: 'Xem chi tiết bất kỳ thành viên nào', module: 'users' },
  { key: 'users:read:self', name: 'Xem hồ sơ chi tiết (Cá nhân)', module: 'users' },
  { key: 'users:create', name: 'Thêm mới thành viên', module: 'users' },
  { key: 'users:update:profile', name: 'Sửa Profile (Họ tên, SĐT, ...)', module: 'users' },
  { key: 'users:update:org', name: 'Sửa Chức vụ / Ban / Khóa', module: 'users' },
  { key: 'users:promote', name: 'Nâng hạng (Promote)', module: 'users' },
  { key: 'users:expel', name: 'Khai trừ (Expel)', module: 'users' },
  { key: 'users:import', name: 'Nhập dữ liệu Excel (Import)', module: 'users' },
  { key: 'users:export', name: 'Xuất dữ liệu Excel (Export)', module: 'users' },
  { key: 'users:delete', name: 'Xóa vĩnh viễn tài khoản', module: 'users' },

  // Lịch trực
  { key: 'duty:view', name: 'Xem lịch trực cơ bản', module: 'duty' },
  { key: 'duty:view:all', name: 'Xem lịch trực toàn đội', module: 'duty' },
  { key: 'duty:register:self', name: 'Đăng ký / Hủy kíp cá nhân', module: 'duty' },
  { key: 'duty:register', name: 'Đăng ký kíp cho thành viên', module: 'duty' },
  { key: 'duty:register:proxy', name: 'Đăng ký / Hủy kíp hộ (Nâng cao)', module: 'duty' },
  { key: 'duty:update', name: 'Cập nhật trạng thái kíp trực', module: 'duty' },
  { key: 'duty:manage', name: 'Quản lý lịch trực (Toàn quyền)', module: 'duty' },
  { key: 'duty:approve_leave', name: 'Phê duyệt đơn nghỉ phép', module: 'duty' },
  { key: 'duty:approve_swap', name: 'Phê duyệt đơn đổi ca', module: 'duty' },
  { key: 'duty:manage:template', name: 'Tạo / Sửa Bản mẫu (Template)', module: 'duty' },
  { key: 'duty:manage:clone', name: 'Dập khuôn lịch tuần', module: 'duty' },
  { key: 'duty:manage:force', name: 'Gắn kíp thủ công (Force assign)', module: 'duty' },
  { key: 'duty:manage:lock', name: 'Khóa kíp (Lock/Disable slot)', module: 'duty' },
  { key: 'duty:attendance', name: 'Điểm danh (Attendance)', module: 'duty' },
  { key: 'duty:violation:report', name: 'Ghi nhận vi phạm (Violation report)', module: 'duty' },

  // Thưởng phạt
  { key: 'reward:create', name: 'Ghi nhận thưởng / phạt', module: 'reward' },
  { key: 'reward:approve', name: 'Duyệt yêu cầu cộng điểm', module: 'reward' },
  { key: 'reward:history:all', name: 'Xem lịch sử (Toàn đội)', module: 'reward' },
  { key: 'reward:history:self', name: 'Xem lịch sử (Cá nhân)', module: 'reward' },
  { key: 'reward:stats:all', name: 'Thống kê tài chính toàn đội', module: 'reward' },
  { key: 'reward:stats:dept', name: 'Thống kê tài chính Ban', module: 'reward' },

  // Họp hành
  { key: 'meeting:create:all', name: 'Tạo lịch họp (Toàn đội)', module: 'meeting' },
  { key: 'meeting:create:dept', name: 'Tạo lịch họp (Ban)', module: 'meeting' },
  { key: 'meeting:attendance', name: 'Điểm danh họp', module: 'meeting' },
  { key: 'meeting:minutes', name: 'Ghi biên bản cuộc họp', module: 'meeting' },

  // Góp ý
  { key: 'feedback:send', name: 'Gửi ý kiến (Ẩn danh/Công khai)', module: 'feedback' },
  { key: 'feedback:receive', name: 'Tiếp nhận & Phân loại ý kiến', module: 'feedback' },
  { key: 'feedback:respond', name: 'Xử lý & Phản hồi ý kiến', module: 'feedback' },

  // Hệ thống
  { key: 'system:roles:view', name: 'Xem danh sách vai trò', module: 'system' },
  { key: 'system:roles:create', name: 'Thêm mới vai trò', module: 'system' },
  { key: 'system:roles:update', name: 'Cập nhật vai trò', module: 'system' },
  { key: 'system:roles:delete', name: 'Xóa vai trò', module: 'system' },
  { key: 'system:permissions:view', name: 'Xem ma trận phân quyền', module: 'system' },
  { key: 'system:permissions:edit', name: 'Chỉnh sửa ma trận phân quyền', module: 'system' },
  { key: 'system:manage:gen', name: 'Cấu hình Niên khóa / Thế hệ', module: 'system' },
  { key: 'system:notify:all', name: 'Gửi thông báo toàn hệ thống', module: 'system' },
  { key: 'system:notify:dept', name: 'Gửi thông báo theo Ban', module: 'system' },

  // Tài liệu
  { key: 'file:upload', name: 'Upload tài liệu minh chứng', module: 'file' },
  { key: 'file:manage:all', name: 'Quản lý kho tài liệu chung', module: 'file' },
  { key: 'file:manage:dept', name: 'Quản lý tài liệu nội bộ Ban', module: 'file' },

  // Đợt cộng điểm & Học kỳ (Bổ sung)
  { key: 'duty:view', name: 'Xem & Đăng ký đợt cộng điểm', module: 'duty' },
  { key: 'duty:manage', name: 'Quản lý toàn bộ đợt cộng điểm', module: 'duty' },
  { key: 'system:manage', name: 'Quản lý cấu hình hệ thống & Học kỳ', module: 'system' },
  { key: 'bonus-campaigns:review', name: 'Xét duyệt chi tiết đăng ký', module: 'bonus-campaigns' },
  { key: 'bonus-campaigns:delete', name: 'Xóa bản đăng ký cộng điểm', module: 'bonus-campaigns' },
];

const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: ['*'],
  ns_leader: [
    'users:list:all',
    'users:list:dept',
    'users:view_stats',
    'users:read:all',
    'users:read:self',
    'users:create',
    'users:update:profile',
    'users:update:org',
    'users:promote',
    'users:expel',
    'users:import',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:register',
    'duty:register:proxy',
    'duty:update',
    'duty:manage',
    'duty:manage:template',
    'duty:manage:clone',
    'duty:manage:force',
    'duty:manage:lock',
    'duty:approve_leave',
    'duty:approve_swap',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:all',
    'reward:history:self',
    'reward:stats:all',
    'reward:stats:dept',
    'meeting:create:all',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:receive',
    'feedback:respond',
    'system:roles:view',
    'system:roles:create',
    'system:roles:update',
    'system:roles:delete',
    'system:permissions:view',
    'system:permissions:edit',
    'system:manage:gen',
    'system:notify:all',
    'system:notify:dept',
    'file:upload',
    'file:manage:all',
    'file:manage:dept',
    'duty:view',
    'duty:manage',
    'system:manage',
    'bonus-campaigns:review',
    'bonus-campaigns:delete',
  ],
  ns_sub_leader: [
    'users:list:all',
    'users:list:dept',
    'users:view_stats',
    'users:read:all',
    'users:read:self',
    'users:create',
    'users:update:profile',
    'users:update:org',
    'users:promote',
    'users:expel',
    'users:import',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:register',
    'duty:register:proxy',
    'duty:update',
    'duty:manage',
    'duty:manage:template',
    'duty:manage:clone',
    'duty:manage:force',
    'duty:manage:lock',
    'duty:approve_leave',
    'duty:approve_swap',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:all',
    'reward:history:self',
    'reward:stats:all',
    'reward:stats:dept',
    'meeting:create:all',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:receive',
    'feedback:respond',
    'system:roles:view',
    'system:roles:create',
    'system:roles:update',
    'system:roles:delete',
    'system:permissions:view',
    'system:permissions:edit',
    'system:manage:gen',
    'system:notify:all',
    'system:notify:dept',
    'file:upload',
    'file:manage:all',
    'file:manage:dept',
    'duty:view',
    'duty:manage',
    'system:manage',
    'bonus-campaigns:review',
    'bonus-campaigns:delete',
  ],
  ns_specialist: [
    'users:list:all',
    'users:list:dept',
    'users:view_stats',
    'users:read:all',
    'users:read:self',
    'users:create',
    'users:update:profile',
    'users:update:org',
    'users:promote',
    'users:expel',
    'users:import',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:register',
    'duty:register:proxy',
    'duty:update',
    'duty:manage',
    'duty:manage:template',
    'duty:manage:clone',
    'duty:manage:force',
    'duty:manage:lock',
    'duty:approve_leave',
    'duty:approve_swap',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:all',
    'reward:history:self',
    'reward:stats:all',
    'reward:stats:dept',
    'meeting:create:all',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:receive',
    'feedback:respond',
    'system:roles:view',
    'system:roles:create',
    'system:roles:update',
    'system:roles:delete',
    'system:permissions:view',
    'system:permissions:edit',
    'system:manage:gen',
    'system:notify:all',
    'system:notify:dept',
    'file:upload',
    'file:manage:all',
    'file:manage:dept',
    'duty:view',
    'duty:manage',
    'system:manage',
    'bonus-campaigns:review',
    'bonus-campaigns:delete',
  ],
  other_leader: [
    'users:list:dept',
    'users:read:all',
    'users:read:self',
    'users:update:profile',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:self',
    'reward:stats:dept',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:respond',
    'system:notify:dept',
    'file:upload',
    'file:manage:dept',
  ],
  tc_leader: [
    'users:list:dept',
    'users:read:all',
    'users:read:self',
    'users:update:profile',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:self',
    'reward:stats:dept',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:respond',
    'system:notify:dept',
    'file:upload',
    'file:manage:dept',
  ],
  tc_sub_leader: [
    'users:list:dept',
    'users:read:all',
    'users:read:self',
    'users:update:profile',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:self',
    'reward:stats:dept',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:respond',
    'system:notify:dept',
    'file:upload',
    'file:manage:dept',
  ],
  tt_leader: [
    'users:list:dept',
    'users:read:all',
    'users:read:self',
    'users:update:profile',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:self',
    'reward:stats:dept',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:respond',
    'system:notify:dept',
    'file:upload',
    'file:manage:dept',
  ],
  tt_sub_leader: [
    'users:list:dept',
    'users:read:all',
    'users:read:self',
    'users:update:profile',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:self',
    'reward:stats:dept',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:respond',
    'system:notify:dept',
    'file:upload',
    'file:manage:dept',
  ],
  other_sub_leader: [
    'users:list:dept',
    'users:read:all',
    'users:read:self',
    'users:update:profile',
    'users:export',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:create',
    'reward:approve',
    'reward:history:self',
    'reward:stats:dept',
    'meeting:create:dept',
    'meeting:attendance',
    'meeting:minutes',
    'feedback:send',
    'feedback:respond',
    'system:notify:dept',
    'file:upload',
    'file:manage:dept',
  ],
  member: [
    'users:read:self',
    'users:update:profile',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:history:self',
    'feedback:send',
    'file:upload',
  ],
  ctv: [
    'users:read:self',
    'users:update:profile',
    'duty:view',
    'duty:view:all',
    'duty:register:self',
    'duty:update',
    'duty:attendance',
    'duty:violation:report',
    'reward:history:self',
    'feedback:send',
    'file:upload',
  ],
  other_role: [],
};

async function seed() {
  try {
    console.log('Connecting to MongoDB...');
    await initDatabase();

    // 1. Clear existing RBAC data
    console.log('Cleaning up existing data...');

    await db.deleteMany('roles', {});
    await db.deleteMany('permissions', {});

    // 2. Insert Permissions
    console.log(`Inserting ${PERMISSIONS.length} permissions...`);
    await db.insertMany('permissions', PERMISSIONS);

    // 3. Clear user-specific overrides to prevent "weird" UI behavior
    console.log('Resetting custom permissions for all users...');
    try {
      const mongoose = require('mongoose');
      if (mongoose.models['users']) {
        await mongoose.models['users'].updateMany({}, { $unset: { customPermissions: 1 } });
      }
    } catch (e) {
      console.warn('Could not reset custom permissions:', e.message);
    }

    // 3. Insert Roles with mapped permissions
    console.log(`Inserting ${ROLES.length} roles...`);
    const rolesToInsert = ROLES.map((role) => ({
      ...role,
      permissions: ROLE_PERMISSIONS[role.key] || [],
    }));
    await db.insertMany('roles', rolesToInsert);

    console.log('RBAC Seed completed successfully!');
  } catch (error) {
    console.error('Seed error:', error);
  } finally {
    process.exit();
  }
}

seed();
